### ISSUE TITLE
你好，有报错信息

### ISSUE THREAD

**Issue by h4rk8s** [Coande/co-wechat-life-export#6]
- 微信版本：7.0.4

- auto.js版本：8.0 pro

- 错误场景：

-使用vscode打开项目，然后连接手机，上传代码，点击运行，再打开微信个人主页用户，提示：
17:52:02.147/E: Thread[main (Spawn-1),5]: TypeError: Cannot call method "children" of null (file:/data/data/org.autojs.autojspro/cache/remote_project/6b934033ff010afaaf7c1bf2502cbf7e/dist/start.js#196(eval)#46)
TypeError: Cannot call method "children" of null
    at file:/data/data/org.autojs.autojspro/cache/remote_project/6b934033ff010afaaf7c1bf2502cbf7e/dist/start.js#196(eval):46:0

- 报错位置：

src/start.js
L38
 const list = id(controlMap.listViewId)
      .findOnce()
      .children();

**Comment by Coande** [comment]
可能微信在不同机型部分界面上元素 id 不一样，导致朋友圈 ListView 元素获取不到，我当时使用的是 MI 6。刚刚尝试了 MI 3，不会在这里报错，但是保存朋友圈图片时有点问题 ~
